name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build website
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          export REACT_APP_API_KEY=$API_KEY
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.API_KEY }}
          publish_dir: ./build/
